swagger: '2.0'
################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "1.0.0"
  title: Publishing Connector Service
  description: |
    Connects to external systems.
schemes:
- http
produces:
- application/json
x-ibm-dx-api-visibility: private
x-ibm-dx-security-user-roles:
- admin
- manager
################################################################################
#                                           Internal APIs                      #
################################################################################
paths:
  /test/marathon:
    get:
      x-ibm-dx-api-visibility: internal
      tags:
      - Internal
      summary: Check Marathon health status.
      responses:
        200:
          description: Service healthy.
        503:
          description: Service unhealthy, restart required.
  /test/consul:
    get:
      x-ibm-dx-api-visibility: internal
      tags:
      - Internal
      summary: Check Consul health status.
      responses:
        200:
          description: All required service-lookups succeeded.
        429:
          description: Service instance may not be able to accept additional load.
        503:
          description: At least one service-lookup could failed.
  /metrics/{name}:
    get:
      x-ibm-dx-api-visibility: internal
      tags:
      - Internal
      summary: Get snapshot of Vert.x application metrics.
      parameters:
      - name: name
        in: path
        description: Prefix of the application metric to fetch (e.g. vertx).
        required: true
        type: string
      responses:
        200:
          description: Vert.x application metrics.
        400:
          description: Application metrics are not enabled.

  /publishing/v1/connector/idc/trigger:
    x-ibm-dx-security-user-roles:
    - admin
    - manager
    post:
      tags:
      - Private
      summary: Triggers this connector.
      parameters:
      - name: rootPageId
        description: The id of the shop root page node. A page with the given ID has to exist in the system, otherwise the call will fail.
        type: string
        required: true
        in: query
      - name: id
        description: The id of this connector. All items generated by the connector get tagged whith this id. Default value is "IdcDefaultConnector"
        type: string
        required: false
        in: query
      - name: idcBaseURL
        description: The base URL of the live IDC server. Default is "https://abj146.watsoncommerce.ibm.com"
        type: string
        required: false
        in: query
      - name: idcPreviewBaseURL
        description: The base URL of the preview IDC server
        type: string
        required: false
        in: query
      - name: storeId
        description: The IDC store ID. Default is "13001"
        type: string
        required: false
        in: query
      - name: urlBasePath
        description: The base URL of the shop pages relative to the site. Default is "/shop"
        type: string
        required: false
        in: query
      - name: pageMappings
        description: The page layout overrides to be applied
        type: string
        required: false
        in: query
      responses:
        200:
          description: |
            Data was successfully connected.
        400:
          $ref: '#/responses/invalid_request'
        500:
          $ref: '#/responses/internal_server_error'
    delete:
      tags:
      - Private
      summary: Removes all dynamic pages created by this connector.
      parameters:
      - name: id
        description: The id of this connector. All items generated by the connector get tagged whith this id. Default value is "IdcDefaultConnector"
        type: string
        required: false
        in: query
      responses:
        204:
          description: |
            Data was successfully deleted.
        400:
          $ref: '#/responses/invalid_request'
        500:
          $ref: '#/responses/internal_server_error'
  /publishing/v1/connector/idc/publish:
    post:
      tags:
      - Private
      summary: Add or update and index documents in the delivery search collection
      parameters:
      - $ref: "#/parameters/requestId"
      - $ref: "#/parameters/dcMappingKey"
      - $ref: "#/parameters/tenant"
      description: |
        The request body contains an array of documents that need to match the schema. Documents of classifications that cannot be processed will be ignored. Supported classifications are 'product' and 'category'. Unfortunately you can not
        define that in Swagger so far.
        ~~~
        {
          "documents": [
            {
              "id": "1",
              "title": "item 1",
              "description": "document description"
            }
          ]
        }
        ~~~
        Documents can be added or updated. So a caller does not need to check if the document exists before the call.
      responses:
        202:
          description: |
            Data was successfully submitted to the publishing infrastructure.
        400:
          $ref: '#/responses/invalid_request'
        500:
          $ref: '#/responses/internal_server_error'


################################################################################
#                                 Parameters                                   #
################################################################################
parameters:
  dcMappingKey:
    name: x-ibm-dx-dc-mapping-key
    in: header
    description: Specifies the data center mapping information of the request tenant.
    required: false
    type: string
  tenant:
    name: x-ibm-dx-tenant-id
    in: header
    description: Specifies the ID of the request tenant.
    required: true
    type: string
  requestId:
    name: x-ibm-dx-request-id
    in: header
    description: Specifies the ID of the request.
    required: false
    type: string



################################################################################
#                                 Responses                                    #
################################################################################
responses:
  invalid_request:
    description: An invalid request was received

  internal_server_error:
    description: Internal server error.
